// <auto-generated />
using System;
using EnerGymAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnerGymAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EnerGymDbContext))]
    [Migration("20260428224649_ActualizacionModelos")]
    partial class ActualizacionModelos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Fecha")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Equipo")
                        .HasColumnType("text");

                    b.Property<string>("GrupoMuscular")
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("Calorias")
                        .HasColumnType("real");

                    b.Property<float?>("Carbohidratos")
                        .HasColumnType("real");

                    b.Property<float?>("Grasas")
                        .HasColumnType("real");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("Proteinas")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.LikePost", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("PostId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LikePosts");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmisorId")
                        .HasColumnType("uuid");

                    b.Property<long>("Fecha")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ReceptorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .HasColumnType("text");

                    b.Property<double>("EnergiaGenerada")
                        .HasColumnType("double precision");

                    b.Property<long>("Fecha")
                        .HasColumnType("bigint");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alergenos")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EsPredisenada")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TiempoPreparacion")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Rutina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EsPredisenada")
                        .HasColumnType("boolean");

                    b.Property<string>("Nivel")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objetivo")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.RutinaEjercicio", b =>
                {
                    b.Property<Guid>("RutinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DescansoSeg")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<float?>("PesoObjetivo")
                        .HasColumnType("real");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int>("Series")
                        .HasColumnType("integer");

                    b.HasKey("RutinaId", "EjercicioId");

                    b.HasIndex("EjercicioId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.SerieRealizada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<Guid>("SesionEntrenamientoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("SesionEntrenamientoId");

                    b.ToTable("SeriesRealizadas");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CaloriasQuemadas")
                        .HasColumnType("integer");

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("integer");

                    b.Property<int?>("EnergiaGeneradaWh")
                        .HasColumnType("integer");

                    b.Property<long>("Fecha")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("RutinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionesEntrenamiento");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("Altura")
                        .HasColumnType("real");

                    b.Property<int?>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objetivo")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("Peso")
                        .HasColumnType("real");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("EnerGymAPI.Domain.Entities.Post", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnerGymAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.LikePost", b =>
                {
                    b.HasOne("EnerGymAPI.Domain.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnerGymAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Likes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("EnerGymAPI.Domain.Entities.Usuario", "Emisor")
                        .WithMany("MensajesEnviados")
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnerGymAPI.Domain.Entities.Usuario", "Receptor")
                        .WithMany("MensajesRecibidos")
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Post", b =>
                {
                    b.HasOne("EnerGymAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Posts")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Receta", b =>
                {
                    b.HasOne("EnerGymAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Recetas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("EnerGymAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Rutina", b =>
                {
                    b.HasOne("EnerGymAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Rutinas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.RutinaEjercicio", b =>
                {
                    b.HasOne("EnerGymAPI.Domain.Entities.Ejercicio", "Ejercicio")
                        .WithMany("RutinasEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnerGymAPI.Domain.Entities.Rutina", "Rutina")
                        .WithMany("RutinasEjercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.SerieRealizada", b =>
                {
                    b.HasOne("EnerGymAPI.Domain.Entities.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnerGymAPI.Domain.Entities.SesionEntrenamiento", "SesionEntrenamiento")
                        .WithMany("SeriesRealizadas")
                        .HasForeignKey("SesionEntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("SesionEntrenamiento");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.HasOne("EnerGymAPI.Domain.Entities.Rutina", "Rutina")
                        .WithMany("Sesiones")
                        .HasForeignKey("RutinaId");

                    b.HasOne("EnerGymAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Ejercicio", b =>
                {
                    b.Navigation("RutinasEjercicios");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Rutina", b =>
                {
                    b.Navigation("RutinasEjercicios");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.Navigation("SeriesRealizadas");
                });

            modelBuilder.Entity("EnerGymAPI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Likes");

                    b.Navigation("MensajesEnviados");

                    b.Navigation("MensajesRecibidos");

                    b.Navigation("Posts");

                    b.Navigation("Recetas");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Rutinas");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
